### ISSUE TITLE
[Tracker] Extension to Evolutionary Algorithms

### ISSUE THREAD

**Issue by veds12** [aidudezzz/deepbots#90]
*Current State*

_Has been released_
---
*TO DO*
- [ ] Add Changelog Automation (PR #87)
- [ ] Integrate PyGAD into the framework
      - [ ] TBD
- [ ] Add Cartpole Example 
      - [ ] TBD
- [ ] Benchmarking
      - [ ] TBD
- [ ] Documentation
---
*Relevant Issues*
* #41  
* #86
